# Project name.
name: tesla-sentrymode

# Project type.
type: php

# Path for index file.
docroot: .

# PHP version.
php_version: '8.4'

# Server type.
webserver_type: nginx-fpm

# Exposed ports for router.
router_http_port: '80'
router_https_port: '443'

# xDebug.
xdebug_enabled: false

# Timezone.
timezone: Europe/Warsaw

# Composer & nodejs versions.
nodejs_version: '24'
composer_version: '2'

# Enables Mutagen asynchronous caching for project.
mutagen_enabled: false

# Add extra webimage packages.
webimage_extra_packages: []

# Web envs.
web_environment:
  # Global settings.
  - ENV=development
